import { MenuNavigations } from '@/types/protal';

const Navigations: MenuNavigations = [
  {
    id: 1,
    tieuDe: 'trang chủ',
    duongDan: '/',
    icon: '',
    parentId: 0,
    sapXep: 1,
    moCuaSoMoi: false,
    children: null,
  },
  {
    id: 2,
    tieuDe: 'giới thiệu',
    duongDan: '/gioi-thieu-thu-vien/',
    icon: '',
    parentId: 0,
    sapXep: 2,
    moCuaSoMoi: false,
    children: [
      {
        id: 21,
        tieuDe: 'Giới thiệu chung',
        duongDan: '/gioi-thieu-thu-vien/',
        icon: '',
        parentId: 2,
        sapXep: 1,
        moCuaSoMoi: false,
      },
      {
        id: 22,
        tieuDe: 'Quy trình làm việc',
        duongDan: '#',
        icon: '',
        parentId: 2,
        sapXep: 2,
        moCuaSoMoi: false,
      },
      {
        id: 23,
        tieuDe: 'Thông báo',
        duongDan: '#',
        icon: '',
        parentId: 2,
        sapXep: 3,
        moCuaSoMoi: false,
      },
      {
        id: 24,
        tieuDe: 'Thư cảm ơn',
        duongDan: '#',
        icon: '',
        parentId: 2,
        sapXep: 4,
        moCuaSoMoi: false,
      },
      {
        id: 25,
        tieuDe: 'Tin tức sự kiện',
        duongDan: '/category/tin-tuc',
        icon: '',
        parentId: 2,
        sapXep: 5,
        moCuaSoMoi: false,
      },
      {
        id: 26,
        tieuDe: 'Hình ảnh hoạt động',
        duongDan: '#',
        icon: '',
        parentId: 2,
        sapXep: 6,
        moCuaSoMoi: false,
      },
      {
        id: 27,
        tieuDe: 'Văn bản pháp quy thư viện',
        duongDan: '#',
        icon: '',
        parentId: 2,
        sapXep: 7,
        moCuaSoMoi: false,
      },
    ],
  },
  {
    id: 3,
    tieuDe: 'hướng dẫn',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 3,
    moCuaSoMoi: false,
    children: null,
  },
  {
    id: 4,
    tieuDe: 'dịch vụ',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 4,
    moCuaSoMoi: false,
    children: [
      {
        id: 41,
        tieuDe: 'Đọc mượn giáo trình, tài liệu',
        duongDan: '#',
        icon: '',
        parentId: 4,
        sapXep: 1,
        moCuaSoMoi: false,
      },
      {
        id: 42,
        tieuDe: 'Phát hành giáo trình, tài liệu nội bộ',
        duongDan: '#',
        icon: '',
        parentId: 4,
        sapXep: 2,
        moCuaSoMoi: false,
      },
      {
        id: 43,
        tieuDe: 'Cung cấp không gian và tiện ích học tập',
        duongDan: '#',
        icon: '',
        parentId: 4,
        sapXep: 3,
        moCuaSoMoi: false,
      },
      {
        id: 44,
        tieuDe: 'Mượn tài liệu thư viện',
        duongDan: '#',
        icon: '',
        parentId: 4,
        sapXep: 4,
        moCuaSoMoi: false,
      },
      {
        id: 45,
        tieuDe: 'Tư vấn và hướng dẫn tìm tín chỉ theo yêu cầu',
        duongDan: '#',
        icon: '',
        parentId: 4,
        sapXep: 5,
        moCuaSoMoi: false,
      },
    ],
  },
  {
    id: 5,
    tieuDe: 'sản phẩm',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 5,
    moCuaSoMoi: false,
    children: [
      {
        id: 51,
        tieuDe: 'Danh mục sách mới',
        duongDan: '#',
        icon: '',
        parentId: 5,
        sapXep: 1,
        moCuaSoMoi: false,
      },
      {
        id: 52,
        tieuDe: 'Giới thiệu sách hay',
        duongDan: '#',
        icon: '',
        parentId: 5,
        sapXep: 2,
        moCuaSoMoi: false,
      },
    ],
  },
  {
    id: 6,
    tieuDe: 'tài nguyên',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 6,
    moCuaSoMoi: false,
    children: [
      {
        id: 61,
        tieuDe: 'Tài liệu giấy',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 1,
        moCuaSoMoi: false,
      },
      {
        id: 62,
        tieuDe: 'Tài liệu số',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 2,
        moCuaSoMoi: false,
      },
      {
        id: 63,
        tieuDe: 'Tài liệu nội bộ',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 3,
        moCuaSoMoi: false,
      },
      {
        id: 64,
        tieuDe: 'Cơ sở dữ liệu',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 4,
        moCuaSoMoi: false,
      },
    ],
  },
];

export { Navigations };
