// import { MenuNavigations } from '@/types/protal';

// const Navigations: MenuNavigations = [
//   // trang chủ
//   {
//     id: 1,
//     tieuDe: 'trang chủ',
//     duongDan: '/',
//     icon: '',
//     parentId: 0,
//     sapXep: 1,
//     moCuaSoMoi: false,
//     children: null,
//   },
//   // giơi thiệu
//   {
//     id: 2,
//     tieuDe: 'giới thiệu',
//     duongDan: '/gioi-thieu-thu-vien/',
//     icon: '',
//     parentId: 0,
//     sapXep: 2,
//     moCuaSoMoi: false,
//     children: [
//       {
//         id: 21,
//         tieuDe: 'Giới thiệu chung',
//         duongDan: '/gioi-thieu-thu-vien/',
//         icon: '',
//         parentId: 2,
//         sapXep: 1,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 22,
//         tieuDe: 'Quy trình làm việc',
//         duongDan: '/gioi-thieu-thu-vien/quy-trinh-lam-viec',
//         icon: '',
//         parentId: 2,
//         sapXep: 2,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 23,
//         tieuDe: 'Thông báo',
//         duongDan: '/category/thong-bao',
//         icon: '',
//         parentId: 2,
//         sapXep: 3,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 24,
//         tieuDe: 'Thư cảm ơn',
//         duongDan: '#',
//         icon: '',
//         parentId: 2,
//         sapXep: 4,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 25,
//         tieuDe: 'Tin tức sự kiện',
//         duongDan: '/category/tin-tuc',
//         icon: '',
//         parentId: 2,
//         sapXep: 5,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 26,
//         tieuDe: 'Hình ảnh hoạt động',
//         duongDan: '/gioi-thieu-thu-vien/hinh-anh-hoat-dong',
//         icon: '',
//         parentId: 2,
//         sapXep: 6,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 27,
//         tieuDe: 'Văn bản pháp quy thư viện',
//         duongDan: '#',
//         icon: '',
//         parentId: 2,
//         sapXep: 7,
//         moCuaSoMoi: false,
//         children: null,
//       },
//     ],
//   },
//   // hướng dẫn
//   {
//     id: 3,
//     tieuDe: 'hướng dẫn',
//     duongDan: '#',
//     icon: '',
//     parentId: 0,
//     sapXep: 3,
//     moCuaSoMoi: false,
//     children: null,
//   },
//   // dịch vụ
//   {
//     id: 4,
//     tieuDe: 'dịch vụ',
//     duongDan: '#',
//     icon: '',
//     parentId: 0,
//     sapXep: 4,
//     moCuaSoMoi: false,
//     // children: [
//     //   {
//     //     id: 41,
//     //     tieuDe: 'Đọc mượn giáo trình, tài liệu',
//     //     duongDan: '#',
//     //     icon: '',
//     //     parentId: 4,
//     //     sapXep: 1,
//     //     moCuaSoMoi: false,
//     //   },
//     //   {
//     //     id: 42,
//     //     tieuDe: 'Phát hành giáo trình, tài liệu nội bộ',
//     //     duongDan: '#',
//     //     icon: '',
//     //     parentId: 4,
//     //     sapXep: 2,
//     //     moCuaSoMoi: false,
//     //   },
//     //   {
//     //     id: 43,
//     //     tieuDe: 'Cung cấp không gian và tiện ích học tập',
//     //     duongDan: '#',
//     //     icon: '',
//     //     parentId: 4,
//     //     sapXep: 3,
//     //     moCuaSoMoi: false,
//     //   },
//     //   {
//     //     id: 44,
//     //     tieuDe: 'Mượn tài liệu thư viện',
//     //     duongDan: '#',
//     //     icon: '',
//     //     parentId: 4,
//     //     sapXep: 4,
//     //     moCuaSoMoi: false,
//     //   },
//     //   {
//     //     id: 45,
//     //     tieuDe: 'Tư vấn và hướng dẫn tìm tín chỉ theo yêu cầu',
//     //     duongDan: '#',
//     //     icon: '',
//     //     parentId: 4,
//     //     sapXep: 5,
//     //     moCuaSoMoi: false,
//     //   },
//     // ],

//     children: [
//       {
//         id: 6163,
//         tieuDe: 'Sinh viên/Học viên',
//         duongDan: '/service/detail-service?Id=1',
//         icon: null,
//         parentId: 6155,
//         sapXep: 1,
//         moCuaSoMoi: false,
//         children: [],
//       },
//       {
//         id: 6164,
//         tieuDe: 'Giảng viên/Nghiên cứu viên',
//         duongDan: '/service/detail-service?Id=2',
//         icon: null,
//         parentId: 6155,
//         sapXep: 2,
//         moCuaSoMoi: false,
//         children: [],
//       },
//       {
//         id: 6165,
//         tieuDe: 'Nhân viên hành chính',
//         duongDan: '/service/detail-service?Id=3',
//         icon: null,
//         parentId: 6155,
//         sapXep: 3,
//         moCuaSoMoi: false,
//         children: [],
//       },
//       {
//         id: 6166,
//         tieuDe: 'Cựu sinh viên',
//         duongDan: '/service/detail-service?Id=4',
//         icon: null,
//         parentId: 6155,
//         sapXep: 4,
//         moCuaSoMoi: false,
//         children: [],
//       },
//       {
//         id: 6167,
//         tieuDe: 'Đối tượng cần hỗ trợ đặc biệt',
//         duongDan: '/service/detail-service?Id=5',
//         icon: null,
//         parentId: 6155,
//         sapXep: 5,
//         moCuaSoMoi: false,
//         children: [],
//       },
//     ],
//   },
//   // sản phẩm
//   {
//     id: 5,
//     tieuDe: 'sản phẩm',
//     duongDan: '#',
//     icon: '',
//     parentId: 0,
//     sapXep: 5,
//     moCuaSoMoi: false,
//     children: [
//       {
//         id: 51,
//         tieuDe: 'Danh mục sách mới',
//         duongDan: '#',
//         icon: '',
//         parentId: 5,
//         sapXep: 1,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 52,
//         tieuDe: 'Giới thiệu sách hay',
//         duongDan: '#',
//         icon: '',
//         parentId: 5,
//         sapXep: 2,
//         moCuaSoMoi: false,
//         children: null,
//       },
//     ],
//   },
//   // tài nguyên
//   {
//     id: 6,
//     tieuDe: 'tài nguyên',
//     duongDan: '#',
//     icon: '',
//     parentId: 0,
//     sapXep: 6,
//     moCuaSoMoi: false,
//     children: [
//       {
//         id: 61,
//         tieuDe: 'Tài liệu giấy',
//         duongDan: '#',
//         icon: '',
//         parentId: 6,
//         sapXep: 1,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 62,
//         tieuDe: 'Tài liệu số',
//         duongDan: '#',
//         icon: '',
//         parentId: 6,
//         sapXep: 2,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 63,
//         tieuDe: 'Tài liệu nội bộ',
//         duongDan: '#',
//         icon: '',
//         parentId: 6,
//         sapXep: 3,
//         moCuaSoMoi: false,
//         children: null,
//       },
//       {
//         id: 64,
//         tieuDe: 'Cơ sở dữ liệu',
//         duongDan: '#',
//         icon: '',
//         parentId: 6,
//         sapXep: 4,
//         moCuaSoMoi: false,
//         children: null,
//       },
//     ],
//   },
// ];

// export { Navigations };

import { MenuNavigations } from '@/types/protal';
import routes from '@/config/route';

const Navigations: MenuNavigations = [
  {
    id: 1,
    tieuDe: 'trang chủ',
    duongDan: routes.trangChu,
    icon: '',
    parentId: 0,
    sapXep: 1,
    moCuaSoMoi: false,
    children: null,
  },
  {
    id: 2,
    tieuDe: 'giới thiệu',
    duongDan: routes.gioiThieuThuVien.goc,
    icon: '',
    parentId: 0,
    sapXep: 2,
    moCuaSoMoi: false,
    children: [
      {
        id: 21,
        tieuDe: 'Giới thiệu chung',
        duongDan: routes.gioiThieuThuVien.gioiThieuChung,
        icon: '',
        parentId: 2,
        sapXep: 1,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 22,
        tieuDe: 'Quy trình làm việc',
        duongDan: routes.gioiThieuThuVien.quyTrinhLamViec,
        icon: '',
        parentId: 2,
        sapXep: 2,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 23,
        tieuDe: 'Thông báo',
        duongDan: routes.chuyenMuc.thongBao,
        icon: '',
        parentId: 2,
        sapXep: 3,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 24,
        tieuDe: 'Thư cảm ơn',
        duongDan: '#',
        icon: '',
        parentId: 2,
        sapXep: 4,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 25,
        tieuDe: 'Tin tức sự kiện',
        duongDan: routes.chuyenMuc.tinTuc,
        icon: '',
        parentId: 2,
        sapXep: 5,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 26,
        tieuDe: 'Hình ảnh hoạt động',
        duongDan: routes.gioiThieuThuVien.hinhAnhHoatDong,
        icon: '',
        parentId: 2,
        sapXep: 6,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 27,
        tieuDe: 'Văn bản pháp quy thư viện',
        duongDan: routes.gioiThieuThuVien.vanBanPhapQuy,
        icon: '',
        parentId: 2,
        sapXep: 7,
        moCuaSoMoi: false,
        children: null,
      },
    ],
  },
  {
    id: 3,
    tieuDe: 'hướng dẫn',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 3,
    moCuaSoMoi: false,
    children: null,
  },
  {
    id: 4,
    tieuDe: 'dịch vụ',
    duongDan: routes.dichVu.goc,
    icon: '',
    parentId: 0,
    sapXep: 4,
    moCuaSoMoi: false,
    children: [
      {
        id: 6163,
        tieuDe: 'Sinh viên/Học viên',
        duongDan: `${routes.dichVu.chiTiet}?Id=1`,
        icon: null,
        parentId: 6155,
        sapXep: 1,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6164,
        tieuDe: 'Giảng viên/Nghiên cứu viên',
        duongDan: `${routes.dichVu.chiTiet}?Id=2`,
        icon: null,
        parentId: 6155,
        sapXep: 2,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6165,
        tieuDe: 'Nhân viên hành chính',
        duongDan: `${routes.dichVu.chiTiet}?Id=3`,
        icon: null,
        parentId: 6155,
        sapXep: 3,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6166,
        tieuDe: 'Cựu sinh viên',
        duongDan: `${routes.dichVu.chiTiet}?Id=4`,
        icon: null,
        parentId: 6155,
        sapXep: 4,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6167,
        tieuDe: 'Đối tượng cần hỗ trợ đặc biệt',
        duongDan: `${routes.dichVu.chiTiet}?Id=5`,
        icon: null,
        parentId: 6155,
        sapXep: 5,
        moCuaSoMoi: false,
        children: [],
      },
    ],
  },
  {
    id: 5,
    tieuDe: 'sản phẩm',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 5,
    moCuaSoMoi: false,
    children: [
      {
        id: 51,
        tieuDe: 'Danh mục sách mới',
        duongDan: '#',
        icon: '',
        parentId: 5,
        sapXep: 1,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 52,
        tieuDe: 'Giới thiệu sách hay',
        duongDan: '#',
        icon: '',
        parentId: 5,
        sapXep: 2,
        moCuaSoMoi: false,
        children: null,
      },
    ],
  },
  {
    id: 6,
    tieuDe: 'tài nguyên',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 6,
    moCuaSoMoi: false,
    children: [
      {
        id: 61,
        tieuDe: 'Tài liệu giấy',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 1,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 62,
        tieuDe: 'Tài liệu số',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 2,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 63,
        tieuDe: 'Tài liệu nội bộ',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 3,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 64,
        tieuDe: 'Cơ sở dữ liệu',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 4,
        moCuaSoMoi: false,
        children: null,
      },
    ],
  },
];

export { Navigations };
