import { MenuNavigationsType } from '@/types/protal';
import routes from '@/constants/routes';

const Navigations: MenuNavigationsType = [
  {
    id: 1,
    tieuDe: 'trang chủ',
    duongDan: routes.trangChu.path,
    icon: '',
    parentId: 0,
    sapXep: 1,
    moCuaSoMoi: false,
    children: null,
  },
  {
    id: 2,
    tieuDe: 'giới thiệu',
    duongDan: routes.gioiThieuThuVien.goc.path,
    icon: '',
    parentId: 0,
    sapXep: 2,
    moCuaSoMoi: false,
    children: [
      {
        id: 21,
        tieuDe: 'Giới thiệu chung',
        duongDan: routes.gioiThieuThuVien.gioiThieuChung.path,
        icon: '',
        parentId: 2,
        sapXep: 1,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 22,
        tieuDe: 'Quy trình làm việc',
        duongDan: routes.gioiThieuThuVien.quyTrinhLamViec.path,
        icon: '',
        parentId: 2,
        sapXep: 2,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 23,
        tieuDe: 'Thông báo',
        duongDan: routes.chuyenMuc.thongBao.path,
        icon: '',
        parentId: 2,
        sapXep: 3,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 24,
        tieuDe: 'Thư cảm ơn',
        duongDan: routes.chuyenMuc.thuCamOn.path,
        icon: '',
        parentId: 2,
        sapXep: 4,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 25,
        tieuDe: 'Tin tức sự kiện',
        duongDan: routes.chuyenMuc.tinTuc.path,
        icon: '',
        parentId: 2,
        sapXep: 5,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 26,
        tieuDe: 'Hình ảnh hoạt động',
        duongDan: routes.gioiThieuThuVien.hinhAnhHoatDong.path,
        icon: '',
        parentId: 2,
        sapXep: 6,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 27,
        tieuDe: 'Văn bản pháp quy thư viện',
        duongDan: routes.gioiThieuThuVien.vanBanPhapQuy.path,
        icon: '',
        parentId: 2,
        sapXep: 7,
        moCuaSoMoi: false,
        children: null,
      },
    ],
  },
  {
    id: 3,
    tieuDe: 'hướng dẫn',
    duongDan: routes.chuyenMuc.huongDan.path,
    icon: '',
    parentId: 0,
    sapXep: 3,
    moCuaSoMoi: false,
    children: null,
  },
  {
    id: 4,
    tieuDe: 'dịch vụ',
    duongDan: routes.dichVu.goc.path,
    icon: '',
    parentId: 0,
    sapXep: 4,
    moCuaSoMoi: false,
    children: [
      {
        id: 6163,
        tieuDe: 'Sinh viên/Học viên',
        duongDan: `${routes.dichVu.dichVuNoiBatChiTiet.path}?Id=1`,
        icon: null,
        parentId: 6155,
        sapXep: 1,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6164,
        tieuDe: 'Giảng viên/Nghiên cứu viên',
        duongDan: `${routes.dichVu.dichVuNoiBatChiTiet.path}?Id=2`,
        icon: null,
        parentId: 6155,
        sapXep: 2,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6165,
        tieuDe: 'Nhân viên hành chính',
        duongDan: `${routes.dichVu.dichVuNoiBatChiTiet.path}?Id=3`,
        icon: null,
        parentId: 6155,
        sapXep: 3,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6166,
        tieuDe: 'Cựu sinh viên',
        duongDan: `${routes.dichVu.dichVuNoiBatChiTiet.path}?Id=4`,
        icon: null,
        parentId: 6155,
        sapXep: 4,
        moCuaSoMoi: false,
        children: [],
      },
      {
        id: 6167,
        tieuDe: 'Đối tượng cần hỗ trợ đặc biệt',
        duongDan: `${routes.dichVu.dichVuNoiBatChiTiet.path}?Id=5`,
        icon: null,
        parentId: 6155,
        sapXep: 5,
        moCuaSoMoi: false,
        children: [],
      },
    ],
  },
  {
    id: 5,
    tieuDe: 'sản phẩm',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 5,
    moCuaSoMoi: false,
    children: [
      {
        id: 51,
        tieuDe: 'Danh mục sách mới',
        duongDan: '#',
        icon: '',
        parentId: 5,
        sapXep: 1,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 52,
        tieuDe: 'Giới thiệu sách hay',
        duongDan: '#',
        icon: '',
        parentId: 5,
        sapXep: 2,
        moCuaSoMoi: false,
        children: null,
      },
    ],
  },
  {
    id: 6,
    tieuDe: 'tài nguyên',
    duongDan: '#',
    icon: '',
    parentId: 0,
    sapXep: 6,
    moCuaSoMoi: false,
    children: [
      {
        id: 61,
        tieuDe: 'Tài liệu giấy',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 1,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 62,
        tieuDe: 'Tài liệu số',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 2,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 63,
        tieuDe: 'Tài liệu nội bộ',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 3,
        moCuaSoMoi: false,
        children: null,
      },
      {
        id: 64,
        tieuDe: 'Cơ sở dữ liệu',
        duongDan: '#',
        icon: '',
        parentId: 6,
        sapXep: 4,
        moCuaSoMoi: false,
        children: null,
      },
    ],
  },
];

export { Navigations };
