import { NewEventsType } from '@/types/portal';

const DataNews: NewEventsType = [
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
  {
    id: 123,
    tieuDe: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ',
    mota: 'Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ Chuyên trang thông tin Chiến dịch Điện Biên Phủ ',
    anhDaiDien: '/news/tu-lieu-dien-bien-phu-300x238.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 1,
  },
  {
    id: 122,
    tieuDe: 'Bài tham dự cuộc chia sẻ góc học tập 2025',
    mota: 'Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 Bài tham dự cuộc chia sẻ góc học tập 2025 ',
    anhDaiDien: '/news/DoNguyenPhuongThao-300x170.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 2,
  },
  {
    id: 121,
    tieuDe: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    mota: 'Thông báo nghỉ lễ ngày Chiến thắng 30/4 và ngày Quốc tế lao động 01/5 năm 2025',
    anhDaiDien: '/news/thong-bao-300x168.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 3,
  },
  {
    id: 120,
    tieuDe: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    mota: 'Đại tướng Võ Nguyên Giáp – chân dung một huyền thoại qua những trang sách',
    anhDaiDien: '/news/dai-tuong-vo-nguyen-giap-300x210.jpg',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 4,
  },
  {
    id: 119,
    tieuDe: 'Sách Người Bạn Tốt Của Chúng Ta',
    mota: 'Sách Người Bạn Tốt Của Chúng Ta',
    anhDaiDien: '/news/van-hoa-doc-2025-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 5,
  },
  {
    id: 6,
    tieuDe: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    mota: 'Thông báo cuộc thi “Chia sẻ góc học tập” – Khoe góc học, rinh quà hot!',
    anhDaiDien: '/news/cuoc-thi-khoe-goc-hoc-300x128.png',
    ngayTao: '2025-03-01T00:00:00',
    loaiId: 6,
  },
];

function getDataNews<T>(page: number, pageSize: number) {
  const totalCount = DataNews.length;
  const totalPages = Math.ceil(totalCount / pageSize);
  const currentPage = Math.max(1, Math.min(page, totalPages)); // đảm bảo trang hợp lệ
  const start = (currentPage - 1) * pageSize;
  const end = start + pageSize;

  return {
    items: DataNews.slice(start, end),
    totalCount,
    pageNumber: currentPage,
    pageSize,
    totalPages,
    hasPreviousPage: currentPage > 1,
    hasNextPage: currentPage < totalPages,
    pageIndex: currentPage - 1,
  };
}
export { DataNews, getDataNews };
