import type { Metadata } from 'next';
import '../styles/globals.css';
import MainHeader from '@/components/layouts/header/main-header';
import { geistMono, geistSans } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
