import {
  Search,
  X,
  ChevronRight,
  ArrowRight,
  ChevronDown,
  Newspaper,
  Calendar,
  Camera,
  QrCode,
  Scan,
  SlidersHorizontal,
  Clock,
  TrendingUp,
  BookOpen,
  BookA,
  FileText,
  Video,
  Music,
  Database,
  Languages,
  MapPin,
  Filter,
  Check,
  RefreshCw,
} from 'lucide-react';

import { FaFacebookF, FaPlusSquare } from 'react-icons/fa';
import { AiOutlineX } from 'react-icons/ai';
import { FaYoutube } from 'react-icons/fa6';

const Icons = {
  search: Search,
  close: X,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  news: Newspaper,
  calendar: Calendar,
  camera: Camera,
  qrCode: QrCode,
  scan: Scan,
  slidersHorizontal: SlidersHorizontal,
  clock: Clock,
  trendingUp: TrendingUp,
  bookOpen: BookOpen,
  bookA: BookA,
  fileText: FileText,
  video: Video,
  music: Music,
  database: Database,
  languages: Languages,
  mapPin: MapPin,
  filter: Filter,
  check: Check,
  refreshCw: RefreshCw,
  facebook: FaFacebookF,
  spaceX: AiOutlineX,
  youtube: FaYoutube,
  plusSquare: FaPlusSquare,
};

export default Icons;
