import {
  Search,
  X,
  ChevronRight,
  ArrowRight,
  ChevronDown,
  Newspaper,
  Calendar,
  Camera,
  QrCode,
  Scan,
  SlidersHorizontal,
  Clock,
  TrendingUp,
  BookOpen,
  BookA,
  FileText,
  Video,
  Music,
  Database,
  Languages,
  MapPin,
  Filter,
  Check,
  RefreshCw,
  Plus,
  Trash,
  Trash2,
  Info,
  Loader,
  User,
  Share2,
  Bookmark,
  Timer,
  Mail,
  Link2,
  AlertCircle,
} from 'lucide-react';

import { FaFacebookF, FaPlusSquare, FaBarcode, FaBuilding, FaFileAlt } from 'react-icons/fa';
import { AiOutlineX } from 'react-icons/ai';
import { FaYoutube } from 'react-icons/fa6';

const Icons = {
  search: Search,
  close: X,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  news: Newspaper,
  calendar: Calendar,
  camera: Camera,
  qrCode: QrCode,
  scan: Scan,
  slidersHorizontal: SlidersHorizontal,
  clock: Clock,
  trendingUp: TrendingUp,
  bookOpen: BookOpen,
  bookA: BookA,
  fileText: FileText,
  video: Video,
  music: Music,
  database: Database,
  languages: Languages,
  mapPin: MapPin,
  filter: Filter,
  check: Check,
  refreshCw: RefreshCw,
  plus: Plus,
  trash: Trash,
  trash2: Trash2,
  info: Info,
  loader: Loader,
  user: User,
  share2: Share2,
  bookmark: Bookmark,
  timer: Timer,
  mail: Mail,
  link2: Link2,
  alertCircle: AlertCircle,
  facebook: FaFacebookF,
  spaceX: AiOutlineX,
  youtube: FaYoutube,
  plusSquare: FaPlusSquare,
  faBarcode: FaBarcode,
  faBuilding: FaBuilding,
  faFileAlt: FaFileAlt,
};

export default Icons;
